version: "3"

volumes:
  node_modules:
  postgres_data:

networks:
  my-network:
    driver: bridge

services:
  db_psql:
    build:
      context: .
      dockerfile: Dockerfile_db
    container_name: ${DB_CONTAINER_NAME}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:${POSTRGRES_DATA}
    networks:
      - my-network

  ws_node:
    build:
      context: .
      dockerfile: Dockerfile_ws
    container_name: ${NODE_CONTAINER_NAME}
    environment:
      - DATABASE_URL=${DB}://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_CONTAINER_NAME}:${DB_PORT}/${POSTGRES_DB}
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    depends_on:
      - db_psql
    volumes:
      - .:${APP_DIRECTORY}
      - node_modules:${APP_DIRECTORY}${MODULES_DIRECTORY}
    networks:
      - my-network
