name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    needs: tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
            node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: tests
        run: npm test

      - name: status
        run: echo "Status ${{ job.status }}."
