name: GitHub Actions

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: codecov/codecov-action@v2
      
      - name: tests
        run: mocha --require mocha-suppress-logs

      - name: status
        run: echo "Status ${{ job.status }}."
