name: main

on:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
            node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      - name: tests
        run: npm test

      - name: Coveralls
        if: github.ref == 'refs/heads/master'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_build_args: |
            TWILIO_AUTH_TOKEN_ARG
            TWILIO_ACCOUNT_SID_ARG
        env:
          HD_DD_AGENT_MAJOR_VERSION: 7
          HD_DD_API_KEY: ${{secrets.DD_API_KEY}}
          HD_DD_DYNO_HOST: true
          TWILIO_AUTH_TOKEN_ARG: ${{secrets.TWILIO_AUTH_TOKEN}}
          TWILIO_ACCOUNT_SID_ARG: ${{secrets.TWILIO_ACCOUNT_SID}}
