name: tests

on:
  push:
    branches:
      - master
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
            node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: tests
        run: npm test

      - name: status
        run: echo "Status ${{ job.status }}."

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
